version: '3.8'

services:
  web:
    build: .
    command: gunicorn taskly.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanagement
    ports:
      - "5432:5432"
